languageCode = "en-us"
title = "Kiali"
theme = "kiali"
baseURL = "https://kiali.io"
relativeURLs = true
ignoreFiles = [ "\\.ignore$" ]

[params]
    custom_css = [
      "/css/kiali_style.css",
      "https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    ]
    maxBlogPosts   = 10

[menu]
  [[menu.main]]
      identifier = "main_news"
      name = "News"
      url = "/news"
      weight = 1
      [[menu.main]]
          identifier = "news_security"
          name = "Security Bulletins"
          url = "/news/security-bulletins"
          weight = 1
          parent = "main_news"
      [[menu.main]]
          identifier = "news_relnotes"
          name = "Release Notes"
          url = "/news/release-notes"
          weight = 2
          parent = "main_news"
  [[menu.main]]
      identifier = "main_quickstart"
      name = "Quick Start"
      url = "/documentation/latest/quick-start"
      weight = 2
  [[menu.main]]
      identifier = "tutorial"
      name = "Tutorial"
      url = "/documentation/latest/tutorial"
      weight = 3
  [[menu.main]]
      identifier = "main_contribute"
      name = "Contribute"
      url = "/contribute"
      weight = 4
  [[menu.main]]
      identifier = "main_doc"
      name = "Documentation"
      url = "/documentation"
      weight = 5
      [[menu.main]]
          identifier = "doc_installation_guide"
          name = "Installation Guide"
          url = "/documentation/latest/installation-guide"
          weight = 1
          parent="main_doc"
      [[menu.main]]
          identifier = "doc_features"
          name = "Features"
          url = "/documentation/latest/features"
          weight = 2
          parent="main_doc"
        [[menu.main]]
          identifier = "topology"
          name = "Topology"
          url = "/documentation/latest/features/topology"
          weight = 1
          parent="doc_features"
        [[menu.main]]
          identifier = "health"
          name = "Health"
          url = "/documentation/latest/features/health"
          weight = 2
          parent="doc_features"
        [[menu.main]]
          identifier = "details"
          name = "Details"
          url = "/documentation/latest/features/details"
          weight = 3
          parent="doc_features"
        [[menu.main]]
          identifier = "tracing"
          name = "Tracing"
          url = "/documentation/latest/features/tracing"
          weight = 4
          parent="doc_features"
        [[menu.main]]
            identifier = "validations"
            name = "Validations"
            url = "/documentation/latest/features/validations"
            weight = 5
            parent="doc_features"
        [[menu.main]]
           identifier = "wizards"
           name = "Wizards"
           url = "/documentation/latest/features/wizards"
           weight = 6
           parent="doc_features"
        [[menu.main]]
           identifier = "configuration"
           name = "Configuration"
           url = "/documentation/latest/features/configuration"
           weight = 7
           parent="doc_features"
        [[menu.main]]
           identifier = "security"
           name = "Security"
           url = "/documentation/latest/features/security"
           weight = 8
           parent="doc_features"
        [[menu.main]]
           identifier = "istio-component-status"
           name = "Istio Status"
           url = "/documentation/latest/features/istio-component-status"
           weight = 9
           parent="doc_features"
        [[menu.main]]
           identifier = "multi-cluster"
           name = "Multi-cluster"
           url = "/documentation/latest/features/multi-cluster"
           weight = 10
           parent="doc_features"
      [[menu.main]]
          identifier = "doc_configuration"
          name = "Configuration"
          url = "/documentation/latest/configuration"
          weight = 3
          parent="main_doc"
          [[menu.main]]
              identifier = "doc_authentication"
              name = "Authentication"
              url = "/documentation/latest/configuration/authentication"
              weight = 1
              parent="doc_configuration"
          [[menu.main]]
              identifier = "doc_rbac"
              name = "RBAC"
              url = "/documentation/latest/configuration/rbac"
              weight = 3
              parent="doc_configuration"
          [[menu.main]]
              identifier = "doc_vm"
              name = "VM Workloads"
              url = "/documentation/latest/configuration/vm"
              weight = 4
              parent="doc_configuration"
      [[menu.main]]
          identifier = "doc_architecture"
          name = "Architecture"
          url = "/documentation/latest/architecture"
          weight = 3
          parent="main_doc"
      [[menu.main]]
          identifier = "doc_glossary"
          name = "Glossary"
          url = "/documentation/latest/glossary"
          weight = 4
          parent="main_doc"
          [[menu.main]]
              identifier = "concepts"
              name = "Concepts"
              url = "/documentation/latest/glossary/concepts"
              weight = 1
              parent="doc_glossary"
          [[menu.main]]
              identifier = "observability"
              name = "Observability"
              url = "/documentation/latest/glossary/observability"
              weight = 2
              parent="doc_glossary"
          [[menu.main]]
              identifier = "networking"
              name = "Networking"
              url = "/documentation/latest/glossary/networking"
              weight = 3
              parent="doc_glossary"
      [[menu.main]]
          identifier = "doc_archive"
          name = "Other Releases"
          url = "/documentation"
          weight = 11
          parent="main_doc"
  [[menu.main]]
      identifier = "main_faq"
      name = "FAQ"
      url = "/documentation/latest/faq"
      weight = 6
