baseURL = "https://staging.kiali.io"
title = "Kiali"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Comment out to disable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"]

# If used, must have same lang as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"]


# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-130444728-1"

# Language configuration

[languages]
[languages.en]
title = "Kiali"
description = "Kiali Project site"
languageName ="English"
# Weight used for sorting.
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "print", "RSS"]

[params]
#copyright = "The Kiali Project"
#privacy_policy = "https://www.redhat.com/en/about/privacy-policy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "latest"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://kiali.io"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/kiali/kiali.io"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/kiali/kiali"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if you have a newer GitHub repo with "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch= "staging"

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "015704640858869259522:6stg794nppg"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
# Set to true to make the sidebar foldable
sidebar_menu_foldable = true
# Uncomment to specify a fixed unfold depth
# sidebar_menu_unfold_depth = 1

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "Kiali channel on Istio Slack"
	url = "https://istio.slack.com/archives/CJVRXB09F"
	icon = "fab fa-slack"
        desc = "Kiali channel on Istio Slack"
[[params.links.user]]
	name ="Kiali on Twitter"
	url = "https://twitter.com/kialiproject"
	icon = "fab fa-twitter"
        desc = "Kiali on Twitter"
[[params.links.user]]
	name = "Kiali on Medium"
	url = "https://medium.com/kialiproject"
	icon = "fab fa-medium-m"
        desc = "Kiali on Medium"
[[params.links.user]]
	name = "Kiali channel on YouTube"
	url = "https://www.youtube.com/channel/UCcm2NzDN_UCZKk2yYmOpc5w"
	icon = "fab fa-youtube"
        desc = "Kiali channel on YouTube"
[[params.links.user]]
	name = "Kiali community calendar"
	url = "https://bit.ly/kiali-calendar"
	icon = "fas fa-calendar"
        desc = "Kiali community calendar"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "Kiali on Github"
	url = "https://github.com/kiali"
	icon = "fab fa-github"
        desc = "Kiali on Github"

# Add your release versions here
[[params.versions]]
  version = "current"
  url = "https://kiali.io"

## NEXT PARAMS.VERSIONS PLACEHOLDER

[[ params.versions ]]
  version = "v1.61"
  url = "https://v1-61.kiali.io"

[[ params.versions ]]
  version = "v1.60"
  url = "https://v1-60.kiali.io"

[[ params.versions ]]
  version = "v1.59"
  url = "https://v1-59.kiali.io"

[[ params.versions ]]
  version = "v1.58"
  url = "https://v1-58.kiali.io"

[[ params.versions ]]
  version = "v1.57 [ossm v2.3]"
  url = "https://v1-57.kiali.io"

[[ params.versions ]]
  version = "v1.56"
  url = "https://v1-56.kiali.io"

[[ params.versions ]]
  version = "v1.55"
  url = "https://v1-55.kiali.io"

[[ params.versions ]]
  version = "v1.54"
  url = "https://v1-54.kiali.io"

[[ params.versions ]]
  version = "v1.53"
  url = "https://v1-53.kiali.io"

[[ params.versions ]]
  version = "v1.52"
  url = "https://v1-52.kiali.io"

[[ params.versions ]]
  version = "v1.51"
  url = "https://v1-51.kiali.io"

[[ params.versions ]]
  version = "v1.50"
  url = "https://v1-50.kiali.io"

[[ params.versions ]]
  version = "v1.49 [istio v1.13]"
  url = "https://v1-49.kiali.io"

[[ params.versions ]]
  version = "v1.48 [ossm v2.2]"
  url = "https://v1-48.kiali.io"

[[ params.versions ]]
  version = "v1.44 [istio v1.12]"
  url = "https://v1-44.kiali.io"

[[ params.versions ]]
  version = "v1.41 [istio v1.11]"
  url = "https://v1-41.kiali.io"

[[params.versions]]
  version = "v1.36 [ossm v2.1]"
  url = "https://pre-v1-41.kiali.io/documentation/v1.36"

[[params.versions]]
  version = "staging"
  url = "https://staging.kiali.io"

[[params.versions]]
  version = "archive"
  url = "https://pre-v1-41.kiali.io"

